"""Adicionando tabela tamanho

Revision ID: 04bbc75958ae
Revises: 84a7be831895
Create Date: 2022-08-15 17:55:47.925871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bbc75958ae'
down_revision = '84a7be831895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanho', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanho')
    # ### end Alembic commands ###
