"""Add tabela usuario

Revision ID: 316602800759
Revises: 69700306a40a
Create Date: 2022-08-16 12:05:09.381989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316602800759'
down_revision = '69700306a40a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
