"""Removendo tabela tamanho

Revision ID: 84a7be831895
Revises: 23b4e19d8a75
Create Date: 2022-08-15 17:54:24.465660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a7be831895'
down_revision = '23b4e19d8a75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanho')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanho', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
